### ISSUE TITLE
chat example does not work on cloud machines.

### ISSUE THREAD

**Issue by froyobin** [libp2p/rust-libp2p#1305] opened 2019-11-14 00:46 UTC
I compile the chat example and test on two cloud machines. It does not work, while the ping example works properly.  Anyone knows the solution? Appreciate

**Comment by cbarraford** [comment] 2019-11-14 04:23
Yeah, i've seen this issue as well. When running the chat example on digital ocean or aws, i cannot get the simple chat example to work. But works just fine in other locations. The behavior i see is that when i type a message and return, the message doesn't show on the other screen (terminal window). Any thoughts on this?

**Comment by thomaseizinger** [comment] 2019-11-14 05:05
The chat examples uses [mDNS](https://en.wikipedia.org/wiki/Multicast_DNS) for discovery which relies on multicast to work in your network.

I suspect that this is purposely deactivated on cloud machines for security reasons. mDNS is not really something you can rely on in production I think. It is cool because it works on local networks but for a production application, you need a more robust discovery protocol like fixed bootnodes and a DHT.

**Comment by froyobin** [comment] 2019-11-14 06:58
@thomaseizinger, appreciate. I am new in the p2p.  Do you have an example of using the DHT or the fix bootnode? Does libp2p provide any robust p2p discovery protocol to use? I try with the example of ipfs-dht, but it seems not working currently.  Thanks for your help!!

**Comment by thomaseizinger** [comment] 2019-11-14 23:55
> @thomaseizinger, appreciate. I am new in the p2p. Do you have an example of using the DHT or the fix bootnode? Does libp2p provide any robust p2p discovery protocol to use? I try with the example of ipfs-dht, but it seems not working currently. Thanks for your help!!

@froyobin Sorry if that sounded harsh, I didn't mean to! :)
I am just a user of rust-libp2p myself, so my knowledge is limited here. What is provided is an implementation of [kademlia](https://docs.libp2p.io/concepts/protocols/#kad-dht): https://github.com/libp2p/rust-libp2p/blob/master/protocols/kad/Cargo.toml

Substrate is a very heavy user of the rust-libp2p library and it has its own discovery behaviour based on kademlia: https://github.com/paritytech/substrate/blob/master/client/network/src/discovery.rs

We took a lot of inspiration in how to use rust-libp2p from that codebase :)

**Comment by froyobin** [comment] 2019-11-15 02:39
@thomaseizinger  Thanks for sharing that link. It is really helpful!!

**Comment by romanb** [comment] 2020-11-03 16:31
Since the chat example using `mDNS` (or be given the address of a peer) is expected, i.e. it is not its intention to demonstrate peer discovery beyond the local network, I think this can be closed as being by design. Thanks for the helpful comments on where to look further for peer discovery.

**Closed by romanb** 2020-11-03 16:31 UTC
