### ISSUE TITLE
protocols/request-response: is_pending_outbound return true right after sending

### ISSUE THREAD

**Issue by mxinden** [libp2p/rust-libp2p#1885] opened 2020-12-11 18:48 UTC
Calling `is_pending_outbound` right after sending a request will return `false` if node is not yet connected to peer. `is_pending_outbound` only checks for requests already initiated on a connection, not requests where a connection still needs to be established.

Diff to reproduce:

```diff
diff --git a/protocols/request-response/tests/ping.rs b/protocols/request-response/tests/ping.rs
index de4d1983..257c9fc9 100644
--- a/protocols/request-response/tests/ping.rs
+++ b/protocols/request-response/tests/ping.rs
@@ -96,6 +96,7 @@ fn ping_protocol() {
         let addr = rx.next().await.unwrap();
         swarm2.add_address(&peer1_id, addr.clone());
         let mut req_id = swarm2.send_request(&peer1_id, ping.clone());
+        assert!(swarm2.is_pending_outbound(&req_id));
 
         loop {
             match swarm2.next().await {
@@ -302,4 +303,3 @@ impl RequestResponseCodec for PingCodec {
         write_one(io, data).await
     }
 }
```

**Comment by whereistejas** [comment] 2021-01-15 09:24
Hi,
As requested in the previous issue, I'm sharing my findings on how to resolve the issue before actually starting to code.

The method we intend to fix is the following:
```rust
    pub fn is_pending_outbound(&self, peer: &PeerId, request_id: &RequestId) -> bool {
        self.connected.get(peer)
            .map(|cs| cs.iter().any(|c| c.pending_inbound_responses.contains(request_id)))
            .unwrap_or(false)
    }
```

The problem is that this method only searches the `pending_inbound_responses` list for the provided the request ID. This fails to look for request IDs that may not have been established, as of, yet. Such request IDs can found in the `pending_outbound_requests` list. So, to resolve to the issue we also need to look for the provided request ID in the second list.

**Comment by mxinden** [comment] 2021-01-15 09:33
Exactly right @whereistejas. Could you create a pull request with the suggested fix, including the small amendment to the unit test, suggested in the initial description?

**Comment by whereistejas** [comment] 2021-01-15 09:35
Sure. In the mean, would you like to assign the issue to me?

**Comment by whereistejas** [comment] 2021-01-15 17:48
Hi,
While writing the code, I noticed that unlike in the case of `pending_inbound_responses` where we can select the particular request ID, this is not possible in the case of `pending_outbound_requests`.

Which led me to just check if the mentioned peer has a pending outbound reqeust.

https://github.com/whereistejas/rust-libp2p/blob/00afae463418f5c01067355be7da82f5dab966ee/protocols/request-response/src/lib.rs#L439

**Comment by romanb** [comment] 2021-01-21 13:50
Closed by https://github.com/libp2p/rust-libp2p/pull/1928.

**Closed by romanb** 2021-01-21 13:50 UTC
Labels: bug, getting-started
