### ISSUE TITLE
cargo doc fail

### ISSUE THREAD

**Issue by Isan-Rivkin** [libp2p/rust-libp2p#620] opened 2018-11-09 11:38 UTC
Hi! Can't wait to use that project :) 

I'm having an issue running `cargo doc`, this is how the first error log looks like: 
I tried solving this errors by quickly commenting out things but it only gave me new errors. 

```
 Documenting net2 v0.2.33
 Documenting base64 v0.9.3
 Documenting bytes v0.4.10
    Checking crossbeam-epoch v0.5.2
 Documenting crossbeam-epoch v0.5.2
    Checking lock_api v0.1.4
 Documenting lock_api v0.1.4
    Checking crunchy v0.1.6
 Documenting crunchy v0.1.6
error: unused extern crate
 --> /home/wildermind/.cargo/registry/src/github.com-1ecc6299db9ec823/base64-0.9.3/src/line_wrap.rs:1:1
  |
1 | extern crate safemem;
  | ^^^^^^^^^^^^^^^^^^^^^ help: remove it
  |
note: lint level defined here
 --> /home/wildermind/.cargo/registry/src/github.com-1ecc6299db9ec823/base64-0.9.3/src/lib.rs:59:57
  |
59|     missing_docs, trivial_casts, trivial_numeric_casts, unused_extern_crates, unused_import_braces,
  |                                                         ^^^^^^^^^^^^^^^^^^^^

error: Compilation failed, aborting rustdoc

error: Could not document `base64`.

Caused by:
  process didn't exit successfully: `rustdoc --crate-name base64 /home/wildermind/.cargo/registry/src/github.com-1ecc6299db9ec823/base64-0.9.3/src/lib.rs -o /home/wildermind/Desktop/tutorials/Rust/rust-libp2p/target/doc -L dependency=/home/wildermind/Desktop/tutorials/Rust/rust-libp2p/target/debug/deps --extern byteorder=/home/wildermind/Desktop/tutorials/Rust/rust-libp2p/target/debug/deps/libbyteorder-d7bd359ca030643e.rmeta --extern safemem=/home/wildermind/Desktop/tutorials/Rust/rust-libp2p/target/debug/deps/libsafemem-572b5764f45fbaae.rmeta` (exit code: 101)
warning: build failed, waiting for other jobs to finish...
error: `[::task::Poll]` cannot be resolved, ignoring it...
   |
note: lint level defined here
  --> /home/wildermind/.cargo/registry/src/github.com-1ecc6299db9ec823/net2-0.2.33/src/lib.rs:42:23
   |
42 | #![deny(missing_docs, warnings)]
   |                       ^^^^^^^^
   = note: #[deny(intra_doc_link_resolution_failure)] implied by #[deny(warnings)]
   = note: the link appears in this line:

            [`Poll::Pending`](::task::Poll). The future will *also* register the
                              ^^^^^^^^^^^^
   = help: to escape `[` and `]` characters, just add '\' before them like `\[` or `\]`

error: `[::task::Context::waker]` cannot be resolved, ignoring it...
   |
   = note: the link appears in this line:

            [`cx.waker()`](::task::Context::waker)). Once a task has been woken up,
                           ^^^^^^^^^^^^^^^^^^^^^^
   = help: to escape `[` and `]` characters, just add '\' before them like `\[` or `\]`

error: Could not document `net2`.

Caused by:
  process didn't exit successfully: `rustdoc --crate-name net2 /home/wildermind/.cargo/registry/src/github.com-1ecc6299db9ec823/net2-0.2.33/src/lib.rs -o /home/wildermind/Desktop/tutorials/Rust/rust-libp2p/target/doc --cfg feature="default" --cfg feature="duration" -L dependency=/home/wildermind/Desktop/tutorials/Rust/rust-libp2p/target/debug/deps --extern cfg_if=/home/wildermind/Desktop/tutorials/Rust/rust-libp2p/target/debug/deps/libcfg_if-3d0543e6c9aa2c11.rmeta --extern libc=/home/wildermind/Desktop/tutorials/Rust/rust-libp2p/target/debug/deps/liblibc-c8bafe997e7019ff.rmeta` (exit code: 101)
warning: build failed, waiting for other jobs to finish...
error: `[::task::Poll]` cannot be resolved, ignoring it...
   |
note: lint level defined here
  --> /home/wildermind/.cargo/registry/src/github.com-1ecc6299db9ec823/bytes-0.4.10/src/lib.rs:71:9
   |
71 | #![deny(warnings, missing_docs, missing_debug_implementations)]
   |         ^^^^^^^^
   = note: #[deny(intra_doc_link_resolution_failure)] implied by #[deny(warnings)]
   = note: the link appears in this line:

            [`Poll::Pending`](::task::Poll). The future will *also* register the
                              ^^^^^^^^^^^^
   = help: to escape `[` and `]` characters, just add '\' before them like `\[` or `\]`

error: `[::task::Context::waker]` cannot be resolved, ignoring it...
   |
   = note: the link appears in this line:

            [`cx.waker()`](::task::Context::waker)). Once a task has been woken up,
                           ^^^^^^^^^^^^^^^^^^^^^^
   = help: to escape `[` and `]` characters, just add '\' before them like `\[` or `\]`

error: Could not document `bytes`.

Caused by:
  process didn't exit successfully: `rustdoc --crate-name bytes /home/wildermind/.cargo/registry/src/github.com-1ecc6299db9ec823/bytes-0.4.10/src/lib.rs -o /home/wildermind/Desktop/tutorials/Rust/rust-libp2p/target/doc -L dependency=/home/wildermind/Desktop/tutorials/Rust/rust-libp2p/target/debug/deps --extern byteorder=/home/wildermind/Desktop/tutorials/Rust/rust-libp2p/target/debug/deps/libbyteorder-d7bd359ca030643e.rmeta --extern iovec=/home/wildermind/Desktop/tutorials/Rust/rust-libp2p/target/debug/deps/libiovec-946a355981f1dd42.rmeta` (exit code: 101)
warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by twittner** [comment] 2018-11-09 12:07
Which rust version and platform do you use? I can successfully run `cargo doc` with rustc 1.30.1 and cargo 1.30.0 on x86_64 Linux. Did you try running `cargo update` to get the newest dependencies?

**Comment by Isan-Rivkin** [comment] 2018-11-09 13:29
@twittner I figured out how to generate docs.
**Short answer:**
I used it as a dependency in an empty new project, it worked.

I wanted to generate the docs from the source tho can't say  what's the problem exactly but for me the issue was: 
I was trying to generate docs from cloning this repo and running `cargo doc` inside (same platform as yours). 
At first, my Rust version was outdated so I upgraded it but then a new error came: 

```
error[E0658]: use of unstable library feature 'rustc_private': this crate is being loaded from the sysroot, an unstable location; did you mean to load this crate from crates.io via `Cargo.toml` instead? (see issue #27812)
 --> src/main.rs:2:1                                                                                                                                                                                        
  |                                                                                                                                                                                                         
2 | extern crate env_logger;                                                                                                                                                                                
  | ^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                                                                
                                                                                                                                                                                                            
error: Compilation failed, aborting rustdoc                                                                                                                                                                 
                                                                                                                                                                                                            
error: Could not document `libp2p`.        
```
I noticed that it's a problem in dev-dependencies [Cargo.toml](https://github.com/libp2p/rust-libp2p/blob/d961e656a74d1bab5366d371a06f9e10d5f4a6c5/Cargo.toml#L44) and it's trying to use some compiler internal macros like `info!`  because `env_logger` need macros defined by `log` crate. 
From the [env_logger]( https://crates.io/crates/env_logger) docs: 

> env_logger makes sense when used in executables (binary projects). Libraries should use the log crate instead

(might want to add that to the dependencies
Then I reallized it would probablly work without the dev-dependencies i.e creating a new project. :)

Thanks.

**Comment by twittner** [comment] 2018-11-09 14:35
Did you create this `src/main.rs` file inside libp2p? If so, please notice that `dev-dependencies` are for tests and you would need to put `env_logger` in the `dependencies` section of `Cargo.toml`. However libp2p is meant to be used as a dependency by other projects, so why putting a `main.rs` into `libp2p/src`?

**Comment by Isan-Rivkin** [comment] 2018-11-09 14:52
Umm, now I didn't create `src/main.rs` which is a very weird error from the log above now when you mention this. Umm, I'm not sure about why is that but I'm pretty sure it was related to the fact that `log` wasn't a dependency because when I added it into the `Cargo.toml` I managed to do `cargo doc` from the source repo. Maybe it's only a problem in something I did and on my machine :)

**Comment by tomaka** [comment] 2018-11-14 13:01
Have you tried running `cargo update`?
I got a weird error related to logs earlier, and updating fixed it.

**Comment by tomaka** [comment] 2020-01-10 15:04
Any problem here is caused by Rust and not by us.
I'll close this, feel free to reopen if there's still an issue.

**Closed by tomaka** 2020-01-10 15:04 UTC
