### ISSUE TITLE
Upgrade to latest tokio (0.2) or switch to async-std?

### ISSUE THREAD

**Issue by daogangtang** [libp2p/rust-libp2p#1318] opened 2019-11-25 07:21 UTC
Hi, is there some plans to upgrade to latest tokio (0.2) or switch to async-std?

Thank you.

**Comment by mxinden** [comment] 2019-11-25 09:21
Hi @daogangtang,

We are currently updating rust-libp2p to use *stable futures* as well as *async/await*. You can follow the progress via the `stable-futures` branch: https://github.com/libp2p/rust-libp2p/tree/stable-futures. Most of the modules only depend on the *async-std* and the *futures* crate.

**Comment by auroraexecution** [comment] 2019-11-26 02:53
Good News!

**Comment by daogangtang** [comment] 2019-11-26 02:54
Good news!

**Comment by vorot93** [comment] 2019-12-11 14:52
Any particular reason for choosing async-std over tokio?

**Comment by tomaka** [comment] 2019-12-11 15:16
> Any particular reason for choosing async-std over tokio?

Initially it's because tokio 0.2 wasn't even a thing.
Now I'd be more keep on picking async-std because they work independently of which executor polls them (contrary to tokio sockets that need a tokio reactor to poll them).

**Comment by carllerche** [comment] 2019-12-11 16:56
You are free to pick whichever you want. I will just clarify some points for future readers of this issue.

Both Tokio and async-std require a reactor to drive socket types. The primary difference is that Tokio __does not__ implicitly start a reactor where as async-std implicitly start background threads from a static context. The advantage of not implicitly starting a reactor is that it allows the user to control how, when, and where the reactor runs (background thread, current thread, inline w/ blocking fn calls, ...).

Tokio sockets support being used from any executor, it just requires you to specify **which** reactor to use to bind them. Roughly, it is something like:

```rust
// start a runtime that only includes an I/O driver
let rt = runtime::Builder::new()
    .enable_io()
    .build()
    .unwrap();

let rt_handle = rt.handle().clone();

// Run the runtime somewhere (background thread?)

let listener = rt_handle.enter(|| tokio::net::TcpListener::bind(...));
```

This has some advantages. For example, `rust-postgres` has seen significant performance improvements by controlling the details of how the I/O driver runs in its sync API bridge.

**Comment by tomaka** [comment] 2019-12-11 18:49
I totally agree that tokio has theoretically better performances. What I'm trying to avoid here is the surprise factor.

I hate the situation where everything compiles just fine, but then produces runtime errors because some initialization process hasn't been performed. In particular, I've been bitten multiple times when it comes to timers, since they appear to instantly succeed if not polled through a reactor of the same tokio version.

In order to be properly documented, one would need to document rust-libp2p and every single API layer on top of it to mention "must be polled through a tokio v0.2 reactor, otherwise it will look like it works but it doesn't".

Is there any discussion about why the old design where you pass a `Handler` when creating sockets was abandoned?

**Comment by carllerche** [comment] 2019-12-11 19:02
I'll respond in more depth in a bit, but could you elaborate on "Just this morning we had a panic in Polkadot ". What was behavior (end result) that lead to a panic? I would expect that an early panic would be more obvious than implicitly having multiple reactors running on the background w/o any indication of this happening?

**Comment by carllerche** [comment] 2019-12-11 20:39
It *sounds* like you want an explicit API where you must specify the runtime handle to use the socket. Otherwise, you you either end up w/ a runtime panic **or** you end up w/ unexpected multiple reactors running in multiple background threads.

Off the top of my head, one option would be to add fns on `runtime::Handle` to create the various resource types (sockets, timouts, ....) and require a feature flag to opt-in to the context based constructors (like `TcpStream::connect`).

So:

```rust
rt_handle.tcp_connect("....").await // -> TcpStream

rt_handle.delay_for(....).await
```

This would probably need to go via an RFC period in an issue.

**Comment by tomaka** [comment] 2019-12-12 11:46
> What was behavior (end result) that lead to a panic?

We were called `tokio0.2::spawn_blocking` from within a `Future` that was polled using `tokio` v0.1. It panics because no tokio environment is detected.

**Comment by en** [comment] 2019-12-12 13:13
> > What was behavior (end result) that lead to a panic?
> 
> We were called `tokio0.2::spawn_blocking` from within a `Future` that was polled using `tokio` v0.1. It panics because no tokio environment is detected.

You may try this https://github.com/tokio-rs/tokio-compat

**Comment by tomaka** [comment] 2019-12-12 13:48
> You may try this https://github.com/tokio-rs/tokio-compat

The problem is not so much *how* to make it work. The fix was done in 5 minutes.
The problem is that we would like to have some guarantee (preferably at compile time) that it is going to work.

**Comment by thomaseizinger** [comment] 2020-01-02 00:38
> > You may try this [tokio-rs/tokio-compat](https://github.com/tokio-rs/tokio-compat)
> 
> The problem is not so much _how_ to make it work. The fix was done in 5 minutes.
> The problem is that we would like to have some guarantee (preferably at compile time) that it is going to work.

I totally understand that reasoning and personally, I'd also appreciate it if there would be compile-time guarantees for this.

It would still be nice to leave the choice up to the end-user on what to use. For example, we make use of a lot of libraries built on top of `hyper` which means we are already using `tokio` anyway.

It is a bit of shame to now having `async-std` being forced upon us by using rust-libp2p, not just in regards of a heavier dependency tree but also with it implicitly spawning a background thread.

Without driving this issue too much off topic: are there any discussions in the community of how to handle this situation? Any shims that wrap both async-std and tokio and allow you to choose the backend through feature flags or something?

**Comment by tomaka** [comment] 2020-01-02 11:48
I'd be in favour of adding tokio equivalents of `TcpConfig` named for example `TokioTcpConfig`.

I think that the default `TcpConfig` should use something that "just works" (i.e. async-std here), but adding alternatives that are more optimized in favour of some trade-off (i.e. here, surprise factor if you're not using tokio) is totally fine.

**Comment by vorot93** [comment] 2020-01-02 13:10
@tomaka Tokio version will *just work* for 99% of users sans a very vocal minority that async-std userbase is.

**Comment by dignifiedquire** [comment] 2020-01-02 13:20
For what it is worth, I am in the other boat, and would like to avoid being forced to use tokio. 

I agree that in theory it would be be great to allow for an easy switch between the two, but all experiments in that regard that I have seen so far looked quite painful to maintain, and quite a lot of overhead for the library authors.

**Comment by vorot93** [comment] 2020-03-21 01:18
@tomaka just to let you know, async-std's executor and I/O runtime seem to be unmaintained since its author is out.
https://twitter.com/stjepang/status/1241028964765913092?s=21

**Comment by tomaka** [comment] 2020-03-23 09:23
> @tomaka just to let you know, async-std's executor and I/O runtime seem to be unmaintained since its author is out.
https://twitter.com/stjepang/status/1241028964765913092?s=21

We're not using async-std's executor. That's the entire point of this whole decision: not being tied to a specific executor. If we used tokio's sockets we would be tied to tokio.

**Comment by tomaka** [comment] 2020-03-23 09:24
As far as I know, all that remains to do before closing this issue is make `libp2p-mdns` socket-agonostic, and then everyone will be happy with that additional bloating.

**Closed** 2020-08-18 12:51 UTC
