### ISSUE TITLE
rust-libp2p Fails to Receive Large Files via Gossipsub from go-libp2p

### ISSUE THREAD

**Issue by frystal** [libp2p/rust-libp2p#4820] opened 2023-11-08 13:39 UTC
### Summary

When using the rust-libp2p, specifically the example/chat as the server, it fails to receive large files sent from a go-libp2p node through the Gossipsub protocol. The issue occurs when attempting to send a file of size 3 * 65535 bytes over the "test-net" topic. The go-libp2p node indicates that the remote rust-libp2p node closes the stream upon attempting this transfer.

### Expected behavior

The rust-libp2p node should be able to receive large files sent from a go-libp2p node via Gossipsub without any issues. The stream should remain open, and the file should be successfully transferred and received by the rust-libp2p node.

### Actual behavior

When the go-libp2p node sends a file of size 3 * 65535 bytes to the rust-libp2p node, the rust-libp2p node appears to close the stream prematurely. 

The log from rust-libp2p:

![image](https://github.com/libp2p/rust-libp2p/assets/44425340/8174f949-8385-44a2-8ad5-ced4ffc402d2)

The log from go-libp2p:

![image](https://github.com/libp2p/rust-libp2p/assets/44425340/d086f31e-d7df-40f0-a446-e0cbd0542701)

### Would you like to work on fixing this bug ?

Maybe

**Comment by dariusc93** [comment] 2023-11-08 18:16
gossipsub max transmit size in rust is 65536 bytes so I can imagine it having issues if its more than that size. Have you tried increasing this to see if it will allow it to go through? The other option might be to chunk the files up into smaller bits of data and piece it together on the receiving end.

https://github.com/libp2p/rust-libp2p/blob/0ef6feb397ede286dcd8c9831dc41fb288426885/protocols/gossipsub/src/protocol.rs#L71

I do believe it closing the stream is intended behaviour. 

https://github.com/libp2p/rust-libp2p/blob/0ef6feb397ede286dcd8c9831dc41fb288426885/protocols/gossipsub/src/handler.rs#L260-L264

**Comment by thomaseizinger** [comment] 2023-11-09 04:38
You can configure the limit here: https://github.com/libp2p/rust-libp2p/blob/0ef6feb397ede286dcd8c9831dc41fb288426885/protocols/gossipsub/src/config.rs#L574-L578

It also seems that the docs are wrong there because the default is 65536 as @dariusc93 pointed out.

**Closed as completed by thomaseizinger** 2023-11-09 04:38 UTC

**Comment by frystal** [comment] 2023-11-09 09:42
Thank you, setting the max_transmit_size to 10 * 65535 allowed the message to be delivered. However, I'm uncertain why such a small value of 65536 was chosen. Since go-libp2p sets the gossipsub message max size to [1<<20](https://github.com/libp2p/go-libp2p-pubsub/blob/b5ee222289aabef29ebf90647d7c0d99d5c8ee19/pubsub.go#L27), the largest gossipsub message from go-libp2p cannot be broadcast to rust-libp2p. I think it could lead to compatibility issues between Go and Rust implementations.


Additionally, the error occurred due to the message size exceeding max_transmit_size. I think it should output a debug message that the message exceeds the limit rather than failing to decode the message?

**Comment by thomaseizinger** [comment] 2023-11-09 10:13
What a meaningful value for the max message size is depends on the concrete topic and the kind of messages you are sending.

You can't have unbounded message sizes anyway so you should test sending & receiving with all your message types.

Furthermore, gossipsub works best as a _notification_ protocol, followed by a 1-to-1 protocol for large data transfer so the max message size shouldn't matter much.

**Comment by mxinden** [comment] 2023-11-09 12:52
> Furthermore, gossipsub works best as a _notification_ protocol, followed by a 1-to-1 protocol for large data transfer so the max message size shouldn't matter much.

Seconding this. Gossipsub is a gossip protocol, hence trades reduced latency for duplication. For large blocks, I suggest looking into `libp2p-request-response` or bitswap.
