### ISSUE TITLE
rust-ipfs? 

### ISSUE THREAD

**Issue by adamski** [libp2p/rust-libp2p#233] opened 2018-06-04 09:00 UTC
I'm looking around for an IPFS implementation I can use in a cross-platform desktop/mobile application. I've been playing with https://github.com/Agorise/c-ipfs, but it seems to be incomplete and unstable from my testing. 

I don't necessary need a full IPFS implementation, but would ideally like to be able to interact with nodes powered by go-ipfs. My use case is "offline first" application user data storage, and I'd like to replace my current dependency on Couchbase server infastructure with IPFS. 

In order to use this library I would need to create a C++ wrapper for it, but it seems that things are moving and changing fast here so I wonder if its better to wait until the API has settled?

**Comment by whyrusleeping** [comment] 2018-06-04 12:05
@adamski With a working libp2p, you can simply connect to any existing ipfs node and start speaking the protocols you want. You would have to reimplement some of those, but the ipfs protocols are actually quite simple. Bitswap is just a single protobuf that you send to request blocks and receive (the same protobuf) to receive those blocks. You could probably implement cpp-ipfs using rust-libp2p pretty easily ;)

**Comment by adamski** [comment] 2018-06-04 12:09
Great, thats very encouraging, thanks.

**Comment by adamski** [comment] 2018-08-10 14:03
Coming back to this - are there any examples of using libp2p to speak to IPFS? Are there any docs that explain some of the terms here, e.g. "protobuf"?

**Comment by adamski** [comment] 2018-09-05 10:14
@tomaka are you able to help with this at all? Any helpful links to similar JS code you can point me to?

**Comment by whyrusleeping** [comment] 2018-09-05 18:29
> are there any examples of using libp2p to speak to IPFS? Are there any docs that explain some of the terms here, e.g. "protobuf"?

Other than ipfs? (ipfs uses libp2p to talk to other ipfs nodes)

What bits do you want to do? If you just want to be able to fetch data from ipfs nodes, you'll want to implement bitswap. The go implementation of that is here: https://github.com/ipfs/go-bitswap

The raw protobuf message is defined here: https://github.com/ipfs/go-bitswap/blob/master/message/pb/message.proto

**Comment by adamski** [comment] 2018-09-06 09:44
Yes, I just want to fetch and provide data to other IPFS nodes. Thanks for the links!

**Comment by adamski** [comment] 2018-10-18 11:12
Does anyone here have a rough idea of days required to implement this? I'm in the process of applying for a research collaboration grant with a local university where implementing rust-ipfs will be the main focus. Thanks.

**Comment by tomaka** [comment] 2018-10-18 11:27
Implementing the *bitswap* protocol (the name of the protocol used by IPFS) shouldn't be very difficult, as far as I know (I haven't looked into it). However you would also need to implement record stores in Kademlia (#146) and create the CLI interface.

**Comment by adamski** [comment] 2018-10-18 11:39
Thanks. I assume that the Kademlia record store is for local storage of other nodes on the network? Would that be based on https://github.com/libp2p/interface-record-store, or more similar to https://github.com/libp2p/js-libp2p-kad-dht?

Is there any documentation that explains some of this stuff?

**Comment by tomaka** [comment] 2018-10-18 12:20
Let's move the discussion to #146

**Comment by dvc94ch** [comment] 2019-02-05 18:52
I got bitswap working. The weird thing is that I always get a negative response to find_provider. By hardcoding `kademlia.find_node(GO_IPFS_PEER_ID.parse().unwrap())` when creating a new behaviour I'll receive the block if I restart the program a couple of times, I assume that is part of the bitswap strategy of the go ipfs node that decides based on previous transactions to send or not send the block.

**Comment by tomaka** [comment] 2019-02-05 21:34
> The weird thing is that I always get a negative response to find_provider.

This might be caused by https://github.com/libp2p/rust-libp2p/issues/694

**Comment by gnunicorn** [comment] 2019-02-11 11:52
@dvc94ch do you have your code available online somewhere?

**Comment by dvc94ch** [comment] 2019-02-11 11:58
There are still some issues with it. I can publish it this week, just haven't gotten around to it yet.

**Comment by dvc94ch** [comment] 2019-02-12 21:21
@tomaka Does the chat example still work in master? I've been struggling with some kind of deadlock problem where the first message is received, but the reply never is, so I've tried tracing calls to NetworkBehaviour and UpgradeInbound/UpgradeOutbound but I can't get the chat example working anymore.

**Comment by dvc94ch** [comment] 2019-02-12 21:57
Never mind, it inexplicably works again after rebooting. weird

**Comment by tomaka** [comment] 2019-02-13 09:48
#910 should have fixed the example sometimes deadlocking.

**Comment by dvc94ch** [comment] 2019-02-13 22:04
I believe the problem is with the mplex muxer. I enabled the yamux muxer and it works. This diff should break the chat application.

```
git diff
diff --git a/src/lib.rs b/src/lib.rs
index c917d18..2cf1d6e 100644
--- a/src/lib.rs
+++ b/src/lib.rs
@@ -219,7 +219,7 @@ pub fn build_tcp_ws_secio_mplex_yamux(local_private_key: secio::SecioKeyPair)
         .and_then(move |out, endpoint| {
             let peer_id = out.remote_key.into_peer_id();
             let peer_id2 = peer_id.clone();
-            let upgrade = core::upgrade::SelectUpgrade::new(yamux::Config::default(), mplex::MplexConfig::new())
+            let upgrade = mplex::MplexConfig::new()
                 // TODO: use a single `.map` instead of two maps
                 .map_inbound(move |muxer| (peer_id, muxer))
                 .map_outbound(move |muxer| (peer_id2, muxer));
```

**Comment by dvc94ch** [comment] 2019-02-14 00:33
@gnunicorn Looking up providers in the dht still doesn't work, but two rust-ipfs clients can exchange blocks if they're on the same LAN. The go-ipfs and js-ipfs clients arent discovered via mdns. 

https://github.com/dvc94ch/rust-ipfs

**Comment by tomaka** [comment] 2019-02-14 09:26
> The go-ipfs and js-ipfs clients arent discovered via mdns.

Go-ipfs and js-ipfs implement mDNS differently than the libp2p specs. I went with following the specs, but the consequence is that we don't discover the Go and Js nodes.

**Comment by adamski** [comment] 2019-02-14 09:47
@dvc94ch thanks for your efforts! 

I think, to make a Rust IPFS implementation as useful as possible it needs to be able to talk to existing Go and JS nodes. But perhaps that is outside the scope of rust-libp2p.

**Comment by gnunicorn** [comment] 2019-02-14 14:42
> Go-ipfs and js-ipfs implement mDNS differently than the libp2p specs. I went with following the specs, but the consequence is that we don't discover the Go and Js nodes.

@tomaka , if you know the difference(s) or can point to what you know to be incompatible, maybe you could put that into a ticket and we can provide a `legacy`-mDNS-crate to allow to connect to them, too?

**Comment by tomaka** [comment] 2019-02-14 14:52
> @tomaka , if you know the difference(s) or can point to what you know to be incompatible, maybe you could put that into a ticket and we can provide a `legacy`-mDNS-crate to allow to connect to them, too?

I don't actually know what they are doing. I sniffed their network traffic and it was very different from what the specifications mention. For the details one would have to read their source code.

I remember talking to someone from Protocol Labs about this, who mentioned that they wanted to eventually switch to what the specifications were.

**Comment by dvc94ch** [comment] 2019-02-14 19:12
> if you know the difference(s) or can point to what you know to be incompatible

I hacked the `js-libp2p-mdns` implementation to work with `rust-libp2p`.
The differences are listed below:
* service name is `_p2p._udp.local` vs `ipfs.local`
* host name is base32 encoded vs base58
* txt record is under `additionals` vs `answers`
* txt record data is `dnsaddr=/multiaddr/p2p/peer_id` vs `peer_id`

In addition to that the `js-libp2p-mdns` implementation sends A, AAAA and SRV records

**Comment by tomaka** [comment] 2019-02-14 19:56
> In addition to that the `js-libp2p-mdns` implementation sends A, AAAA and SRV records

Yeah, #734

**Comment by adamski** [comment] 2019-02-14 20:18
What's the likelihood of `js-libp2p-mdns` changing to adhere to the specs anytime soon? I imagine it might break things if they change it..

For my particular use case, I don't mind having only nodes I set up being discoverable (local / remote data replication), but eventually I want to be able to have those nodes discoverable by JS and Go nodes and vice versa.

**Comment by gnunicorn** [comment] 2019-02-20 14:33
> I hacked the `js-libp2p-mdns` implementation to work with `rust-libp2p`.
> The differences are listed below:
>
>     * service name is `_p2p._udp.local` vs `ipfs.local` 
>     * host name is base32 encoded vs base58
>     * txt record is under `additionals` vs `answers`
>     * txt record data is `dnsaddr=/multiaddr/p2p/peer_id` vs `peer_id`

Curious. Running `go-ipfs`, reporting unknown messages, I can see the query name as `_ipfs-discovery._udp.local` and `l08d3t9uspkq8q9q6vhmjprlh1rgcj8c0rrf951fvkmq5b3xn5fckc1._p2p._udp.local` (the beginning being the `peer id` I assume). Are go-ipfs and the js-version incompatible to one another :thinking: ?

**Comment by dignifiedquire** [comment] 2019-02-20 15:37
I think @richardschneider worked on this interop last, maybe they can clear something up.

**Comment by gnunicorn** [comment] 2019-02-20 16:16
Indeed a known issue: https://github.com/libp2p/go-libp2p/issues/176#issuecomment-366776091

**Comment by gnunicorn** [comment] 2019-02-26 07:22
#968 is now able to discover legacy IPFS clients in js and go. However, as both of them are technically specific to the ipfs-domain, I am not sure we want to have that code in the regular libp2p code, but also don't really see a way to make it more generic or nicer. I am thinking of future-gating it...

**Comment by dvc94ch** [comment] 2019-02-26 09:52
@gnunicorn maybe the best solution is the one all large corporations use. Write a spec for the rust-libp2p-mdns implementation, get it accepted in libp2p/specs and let every one else fix their code.

**Comment by tomaka** [comment] 2019-02-26 10:39
> Write a spec for the rust-libp2p-mdns implementation, get it accepted in libp2p/specs and let every one else fix their code.

There's also a specs and the rust-libp2p-mdns implementation follows it. We're basically at the last step.

**Comment by dvc94ch** [comment] 2019-02-26 11:03
Some things are specific to rust-libp2p no? Like the service tag must be `_p2p._udp.local` and that dnsaddr must be a valid `{multiaddr}/p2p/{PeerId}` and that implementations must provide a `TXT` record with a valid dnsaddr.

**Comment by tomaka** [comment] 2019-02-26 13:21
That's exactly what is specified here: https://github.com/libp2p/specs/blob/2f3e55d391338a32a7cb67e4e4aa7b78d02e0d8c/discovery/mdns.md

**Comment by dvc94ch** [comment] 2019-02-26 13:49
Hadn't seen it because it's not in master... Thanks! So @gnunicorn and I found an issue where the multiaddr returned by the legacy mdns was unsupported which is fixed now and that the jsipfs node fails an identity check if you attempt to connect before the peer was discovered. I'm not sure what the next steps are other than waiting.

**Comment by folex** [comment] 2019-12-26 15:32
> I hacked the js-libp2p-mdns implementation to work with rust-libp2p.
@dvc94ch Hi! Do you, by any chance, have this hack available somewhere? I'm trying to connect rust-libp2p with js-libp2p, and having all kind of troubles. mDNS is one of them.

**Comment by dvc94ch** [comment] 2019-12-26 15:38
https://github.com/dvc94ch/js-libp2p-mdns/commits/master

**Comment by tomaka** [comment] 2020-02-11 09:24
cc https://github.com/ipfs/infra/issues/496

**Closed** 2021-02-23 14:53 UTC
Labels: difficulty:moderate
