### ISSUE TITLE
meta: Unify how tests are written

### ISSUE THREAD

**Issue by umgefahren** [libp2p/rust-libp2p#3116] opened 2022-11-13 15:41 UTC
## Description

While going through a lot of tests in #3097 I discovered that pretty much every module has its way of testing. Meaning transports, Swarm creation, async runtime, and general patterns. Sometimes it was quite hard to understand the tests and/or replace the deprecated APIs. We should maybe agree on a standard way how to do testing, and maybe introduce a libp2p-test, to make tests more maintainable.

## Motivation

Understanding and changing old tests are hard in many instances. To improve maintainability we should unify here. 

## Are you planning to do it yourself in a pull request?

Maybe.

**Comment by mxinden** [comment] 2022-11-13 17:42
Related: https://github.com/libp2p/rust-libp2p/pull/2888/

**Comment by mxinden** [comment] 2022-11-13 17:43
Related: https://github.com/libp2p/rust-libp2p/pull/2888/

**Comment by thomaseizinger** [comment] 2022-11-13 22:01
Closing as a duplicate of #2884.

Let me know if #2884 doesn't cover everything. Happy to merge patches against #2888 to move it forward :)

**Closed as not planned** 2022-11-13 22:01 UTC
