### ISSUE TITLE
WebAssembly example

### ISSUE THREAD

**Issue by YoshieraHuang** [libp2p/rust-libp2p#2589] opened 2022-03-24 11:28 UTC
It seems a lot of efforts have been done to bring this crate to web. It will be better that some one can provide an example about how to run this crate on web.

**Comment by mxinden** [comment] 2022-03-25 08:44
Very much agreed. A tutorial in `src/tutorials/` would be great. 

I am closing here as a duplicate of https://github.com/libp2p/rust-libp2p/issues/23.

**Closed as completed by mxinden** 2022-03-25 08:44 UTC
