### ISSUE TITLE
Couldn't compile rust-libp2p/examples/ping.rs

### ISSUE THREAD

**Issue by fishseabowl** [libp2p/rust-libp2p#2386] opened 2021-12-15 22:41 UTC
When I use cargo run, I got the below errors:
error[E0433]: failed to resolve: could not find `Behaviour` in `ping`
  --> src/main.rs:14:27
   |
14 |     let behaviour = ping::Behaviour::new(ping::Config::new().with_keep_alive(true));
   |                           ^^^^^^^^^ could not find `Behaviour` in `ping`

error[E0433]: failed to resolve: could not find `Config` in `ping`
  --> src/main.rs:14:48
   |
14 |     let behaviour = ping::Behaviour::new(ping::Config::new().with_keep_alive(true));
   |                                                ^^^^^^ could not find `Config` in `ping`

error[E0308]: mismatched types
  --> src/main.rs:22:20
   |
22 |         swarm.dial(remote);
   |                    ^^^^^^ expected `&PeerId`, found struct `Multiaddr`
    

My cargo.toml is as:
[dependencies]
either = "1.6.0"
futures = "0.3.9"
libp2p = "0.39.0"
log = "0.4"
rand = "0.7"
smallvec = "1.6.1"
void = "1"
futures-timer = "3.0.2"
instant = "0.1.11"
async-std = { version = "1.7.0", features = ["attributes"] }

**Comment by thomaseizinger** [comment] 2021-12-16 00:42
I cannot reproduce this locally. On latest master and also the version you are depending on (0.39.0) the following works fine for me (inside the rust-libp2p repository):

latest master:

```
❯ pwd
/home/thomas/src/github.com/libp2p/rust-libp2p
❯ cargo run --example ping
    Finished dev [unoptimized + debuginfo] target(s) in 0.18s
     Running `/home/thomas/.cache/cargo/target/debug/examples/ping`
Local peer id: PeerId("12D3KooWCSy4x6iSKJ3vKXUwSmyHcJrQdJEoZD6WLamUavhASRjP")
Listening on "/ip4/127.0.0.1/tcp/42205"
Listening on "/ip4/192.168.188.20/tcp/42205"
Listening on "/ip4/10.10.0.1/tcp/42205"
Listening on "/ip4/172.17.0.1/tcp/42205"
```

v0.39.0:

```
❯ pwd
/home/thomas/src/github.com/libp2p/rust-libp2p
❯ cargo run --example ping
warning: field is never read: `marker`
   --> core/src/transport/and_then.rs:142:5
    |
142 |     marker: PhantomPinned,
    |     ^^^^^^^^^^^^^^^^^^^^^
    |
    = note: `#[warn(dead_code)]` on by default

warning: `libp2p-core` (lib) generated 1 warning
    Finished dev [unoptimized + debuginfo] target(s) in 0.16s
     Running `/home/thomas/.cache/cargo/target/debug/examples/ping`
Local peer id: PeerId("12D3KooWBKKzcHpFkxZGn68UXQtESYdXPh1k3dcDMELzV3w3gZGT")
Listening on "/ip4/127.0.0.1/tcp/39143"
Listening on "/ip4/192.168.188.20/tcp/39143"
Listening on "/ip4/10.10.0.1/tcp/39143"
Listening on "/ip4/172.17.0.1/tcp/39143"
```

You might be running the examples wrongly. Are you using `cargo run --example ping`?

Examples are compile-checked with every `cargo test` which is enforces to be green on our CI so it is kind of impossible that the examples don't compile. Did you maybe just copy-paste the example from latest master and tried running it against an older release? Because that won't work and is not supported. You need to look at [the examples for the release that you are using](https://github.com/libp2p/rust-libp2p/blob/v0.39.1/examples/ping.rs) (which is outdated for you btw).

**Comment by thomaseizinger** [comment] 2021-12-16 00:43
Closing this for now, please ping if you are still having troubles :)

**Closed as completed by thomaseizinger** 2021-12-16 00:43 UTC
