### ISSUE TITLE
Kademlia tests sometimes fail

### ISSUE THREAD

**Issue by twittner** [libp2p/rust-libp2p#1053] opened 2019-04-11 11:20 UTC
The kademlia tests sometimes fail, [for example](https://circleci.com/gh/libp2p/rust-libp2p/12310):

```
running 13 tests
thread 'tokio-runtime-worker-0' panicked at 'assertion failed: `(left == right)`
  left: `0`,
 right: `2`', protocols/kad/src/behaviour/test.rs:141:29
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
test behaviour::test::direct_query ... FAILED
test behaviour::test::basic_find_node ... ok
test behaviour::test::unresponsive_not_returned_direct ... ok
test behaviour::test::indirect_query ... ok
test kbucket::tests::basic_closest ... ok
test kbucket::tests::distance_correct_order ... ok
test behaviour::test::unresponsive_not_returned_indirect ... ok
test kbucket::tests::self_distance_zero ... ok
test kbucket::tests::update_local_id_fails ... ok
test query::tests::continue_second_result ... ok
test query::tests::start_by_sending_rpc_to_known_peers ... ok
test query::tests::timeout_works ... ok
test kbucket::tests::full_kbucket ... ok

failures:

---- behaviour::test::direct_query stdout ----
thread 'behaviour::test::direct_query' panicked at 'called `Result::unwrap()` on an `Err` value: Canceled', src/libcore/result.rs:997:5


failures:
    behaviour::test::direct_query

test result: FAILED. 12 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out
```

[Another one](https://circleci.com/gh/libp2p/rust-libp2p/12324):

```
running 13 tests
test behaviour::test::basic_find_node ... ok
test behaviour::test::direct_query ... ok
test behaviour::test::unresponsive_not_returned_direct ... ok
thread 'tokio-runtime-worker-1' panicked at 'assertion failed: `(left == right)`
  left: `0`,
 right: `3`', protocols/kad/src/behaviour/test.rs:190:29
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
test behaviour::test::indirect_query ... FAILED
test kbucket::tests::basic_closest ... ok
test kbucket::tests::distance_correct_order ... ok
test behaviour::test::unresponsive_not_returned_indirect ... ok
test kbucket::tests::self_distance_zero ... ok
test kbucket::tests::update_local_id_fails ... ok
test query::tests::continue_second_result ... ok
test query::tests::start_by_sending_rpc_to_known_peers ... ok
test query::tests::timeout_works ... ok
test kbucket::tests::full_kbucket ... ok

failures:

---- behaviour::test::indirect_query stdout ----
thread 'behaviour::test::indirect_query' panicked at 'called `Result::unwrap()` on an `Err` value: Canceled', src/libcore/result.rs:997:5


failures:
    behaviour::test::indirect_query

test result: FAILED. 12 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out
```

**Comment by twittner** [comment] 2019-04-11 12:25
This happened after the switch from TCP to memory transport in those tests.

**Comment by montekki** [comment] 2019-04-17 16:25
I was looking into it and so here is what i found: there are two types of random variables in the tests that can cause randomly occuring failures: `base_ports` of the memory transports and the `PeerId`s derived from randomly generated keys.

After some search for fails I came up with a number of pre-set `PeerId`s that help reproduce the failure (possibly) in `direct_query` test, however other tests fail too from time to time. Here it is: https://github.com/montekki/rust-libp2p/commit/f80482379995590cdaa6623176d3fb932ec2e66e 

Since we do not connect the nodes together in the `build_nodes` , that failure must not come from `secio` denying the connection (because the hardcoded `PeerId`s do not match the `local_key`).

**Comment by tomaka** [comment] 2019-04-17 16:35
I think that this is most likely some issue with Kademlia thinking that an RPC query has failed while it is still in progress.

Switching to the memory transport and hardcoding PeerId changes the timing of the connections (ie. in which order connections are attempted and established), which could reveal the issue.

I think a good start would be to log the events that the `RawSwarm` emits (most importantly: connected, disconnected, dial failure, and replaced), and compare the events when the test succeeds and when it fails.

**Comment by montekki** [comment] 2019-04-17 16:43
but the code says that the nodes are not connected:
```
/// Builds swarms, each listening on a port. Does *not* connect the nodes together.
```
and we add addrs to swarms with `add_not_connected_address`?

**Comment by tomaka** [comment] 2019-04-17 16:46
Yes, `add_not_connected_address` "connects" the two swarm by indicating to the second one the address of the first one.
The word "connect" is a bit misleading, they actually connect (as in, establish a connection) only when we actually run the tests in the tokio runtime.

**Comment by tomaka** [comment] 2019-04-23 13:23
cc @elferdo could you look into this semi-urgently?

**Comment by montekki** [comment] 2019-04-23 13:51
I have been able to collect some traces of normal execution vs failures last week, however diff-ing them does not hint any solution. Also it looks like as you add more logging the tests become more stable, since logging affects timings.

I could probably proceed running the tests in the background, though

**Comment by elferdo** [comment] 2019-04-23 13:55
> cc @elferdo could you look into this semi-urgently?

Sure, let me have a look at it

**Comment by elferdo** [comment] 2019-04-23 16:35
I can reproduce the errors simply changing `from_secs` to `from_millis` in https://github.com/libp2p/rust-libp2p/blob/a375d558b10356498f41de85f94fe637153316ea/protocols/kad/src/behaviour.rs#L264

I can't say this is the root cause, but it would be consistent with @tomaka's observations. Now, eight seconds look quite a reasonable timeout for an in-memory channel. Do we have any estimation of how often the error occurs in our test server? We could raise the timeout and see if it happens less often.

**Comment by elferdo** [comment] 2019-04-23 16:40
Interestingly, running the two tests takes as long as this timeout:

```
time cargo test -p libp2p-kad direct_query
    Finished dev [unoptimized + debuginfo] target(s) in 0.20s
     Running target/debug/deps/libp2p_kad-858aa864e60e38bd

running 2 tests
test behaviour::test::direct_query ... ok
test behaviour::test::indirect_query ... ok
[...]
cargo test -p libp2p-kad direct_query  0,71s user 0,06s system 9% cpu 8,461 total
```

**Comment by romanb** [comment] 2019-05-05 10:26
I addressed the observation made here that many queries always take at least `rpc_timeout` seconds in https://github.com/libp2p/rust-libp2p/pull/1097. Beyond that, I'm currently unable to reproduce these failures locally without changing the `rpc_timeout` to a very low value, in which case these failures are actually expected.

@montekki The test case with the preset peer IDs you provided in https://github.com/libp2p/rust-libp2p/issues/1053#issuecomment-484162659 only fails due to a [peer ID mismatch in the Swarm](https://github.com/libp2p/rust-libp2p/issues/1053#issuecomment-484162659) (the secio handshake works fine), since your setup always tells the Swarm to expect the node's local peer ID, but the output of the secio handshake will return the actual remote's peer ID.

If someone manages to reproduce these errors with the current state of `master`, even just a single occurrence, please let me know here. Even though they may be genuine (i.e. parallel tests or other causes for the CPUs on CI being hogged for a couple seconds), it is still a bit suspect that these occasional CI failures started roughly around https://github.com/libp2p/rust-libp2p/commit/6917b8f543d235c3f5838ed44ad3f903506286e8 which also switched the tests to the `MemoryTransport`, as @twittner noted. Meanwhile I will continue to watch out for these failures and update this issue if there is any news.

**Comment by romanb** [comment] 2019-07-11 09:12
I'm closing this since a lot of changes have been made since and it seems to me that these errors no longer occur, but anyone should feel free to reopen this issue (ideally with new / more recent information) in case of new incidents.

**Closed by romanb** 2019-07-11 09:12 UTC
Labels: bug, difficulty:hard
