### ISSUE TITLE
Panic in `libp2p-websocket` at 'SinkImpl::poll_ready called after error.'

### ISSUE THREAD

**Issue by hrxi** [libp2p/rust-libp2p#2598] opened 2022-03-29 23:19 UTC
```
Mar 24 02:52:40 ip-172-31-13-88 nimiq-client[36147]:    0: log_panics::init::{{closure}}
Mar 24 02:52:40 ip-172-31-13-88 nimiq-client[36147]:    1: std::panicking::rust_panic_with_hook
Mar 24 02:52:40 ip-172-31-13-88 nimiq-client[36147]:              at /rustc/3c17c84a386e7badf6b2c6018d172496b3a28a04/library/std/src/panicking.rs:702:17
Mar 24 02:52:40 ip-172-31-13-88 nimiq-client[36147]:    2: std::panicking::begin_panic::{{closure}}
Mar 24 02:52:40 ip-172-31-13-88 nimiq-client[36147]:    3: std::sys_common::backtrace::__rust_end_short_backtrace
Mar 24 02:52:40 ip-172-31-13-88 nimiq-client[36147]:    4: std::panicking::begin_panic
Mar 24 02:52:40 ip-172-31-13-88 nimiq-client[36147]:    5: <quicksink::SinkImpl<S,F,T,A,E> as futures_sink::Sink<A>>::poll_ready
Mar 24 02:52:40 ip-172-31-13-88 nimiq-client[36147]:    6: <rw_stream_sink::RwStreamSink<S> as futures_io::if_std::AsyncWrite>::poll_write
Mar 24 02:52:40 ip-172-31-13-88 nimiq-client[36147]:    7: <multistream_select::negotiated::Negotiated<TInner> as futures_io::if_std::AsyncWrite>::poll_write
Mar 24 02:52:40 ip-172-31-13-88 nimiq-client[36147]:    8: <libp2p_noise::io::framed::NoiseFramed<T,S> as futures_sink::Sink<&alloc::vec::Vec<u8>>>::poll_ready
Mar 24 02:52:40 ip-172-31-13-88 nimiq-client[36147]:    9: <libp2p_noise::io::framed::NoiseFramed<T,S> as futures_sink::Sink<&alloc::vec::Vec<u8>>>::poll_flush
Mar 24 02:52:40 ip-172-31-13-88 nimiq-client[36147]:   10: <libp2p_noise::io::NoiseOutput<T> as futures_io::if_std::AsyncWrite>::poll_flush
Mar 24 02:52:40 ip-172-31-13-88 nimiq-client[36147]:   11: multistream_select::negotiated::Negotiated<TInner>::poll
Mar 24 02:52:40 ip-172-31-13-88 nimiq-client[36147]:   12: <multistream_select::negotiated::Negotiated<TInner> as futures_io::if_std::AsyncWrite>::poll_close
Mar 24 02:52:40 ip-172-31-13-88 nimiq-client[36147]:   13: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
Mar 24 02:52:40 ip-172-31-13-88 nimiq-client[36147]:   14: <S as futures_core::stream::TryStream>::try_poll_next
Mar 24 02:52:40 ip-172-31-13-88 nimiq-client[36147]:   15: <futures_util::stream::try_stream::ErrInto<St,E> as futures_core::stream::Stream>::poll_next
Mar 24 02:52:40 ip-172-31-13-88 nimiq-client[36147]:   16: <libp2p_yamux::Yamux<S> as libp2p_core::muxing::StreamMuxer>::close
Mar 24 02:52:40 ip-172-31-13-88 nimiq-client[36147]:   17: <libp2p_core::muxing::Wrap<T> as libp2p_core::muxing::StreamMuxer>::close
Mar 24 02:52:40 ip-172-31-13-88 nimiq-client[36147]:   18: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
Mar 24 02:52:40 ip-172-31-13-88 nimiq-client[36147]:   19: tokio::runtime::task::harness::poll_future
Mar 24 02:52:40 ip-172-31-13-88 nimiq-client[36147]:   20: tokio::runtime::task::harness::Harness<T,S>::poll
Mar 24 02:52:40 ip-172-31-13-88 nimiq-client[36147]:   21: std::thread::local::LocalKey<T>::with
Mar 24 02:52:40 ip-172-31-13-88 nimiq-client[36147]:   22: tokio::runtime::thread_pool::worker::Context::run_task
Mar 24 02:52:40 ip-172-31-13-88 nimiq-client[36147]:   23: tokio::runtime::thread_pool::worker::Context::run
Mar 24 02:52:40 ip-172-31-13-88 nimiq-client[36147]:   24: tokio::macros::scoped_tls::ScopedKey<T>::set
Mar 24 02:52:40 ip-172-31-13-88 nimiq-client[36147]:   25: tokio::runtime::thread_pool::worker::run
Mar 24 02:52:40 ip-172-31-13-88 nimiq-client[36147]:   26: tokio::runtime::task::harness::Harness<T,S>::poll
Mar 24 02:52:40 ip-172-31-13-88 nimiq-client[36147]:   27: tokio::runtime::blocking::pool::Inner::run
Mar 24 02:52:40 ip-172-31-13-88 nimiq-client[36147]:   28: std::sys_common::backtrace::__rust_begin_short_backtrace
Mar 24 02:52:40 ip-172-31-13-88 nimiq-client[36147]:   29: core::ops::function::FnOnce::call_once{{vtable.shim}}
Mar 24 02:52:40 ip-172-31-13-88 nimiq-client[36147]:   30: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
Mar 24 02:52:40 ip-172-31-13-88 nimiq-client[36147]:              at /rustc/3c17c84a386e7badf6b2c6018d172496b3a28a04/library/alloc/src/boxed.rs:1853:9
Mar 24 02:52:40 ip-172-31-13-88 nimiq-client[36147]:       <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
Mar 24 02:52:40 ip-172-31-13-88 nimiq-client[36147]:              at /rustc/3c17c84a386e7badf6b2c6018d172496b3a28a04/library/alloc/src/boxed.rs:1853:9
Mar 24 02:52:40 ip-172-31-13-88 nimiq-client[36147]:       std::sys::unix::thread::Thread::new::thread_start
Mar 24 02:52:40 ip-172-31-13-88 nimiq-client[36147]:              at /rustc/3c17c84a386e7badf6b2c6018d172496b3a28a04/library/std/src/sys/unix/thread.rs:108:17
Mar 24 02:52:40 ip-172-31-13-88 nimiq-client[36147]:   31: start_thread
Mar 24 02:52:40 ip-172-31-13-88 nimiq-client[36147]:   32: clone
```

I don't know how to reproduce the bug, but it seemed likely to be fixable without reproduction.

CC https://github.com/nimiq/core-rs-albatross/issues/732

**Comment by tomaka** [comment] 2022-06-13 08:22
I believe the issue might be here: https://github.com/libp2p/rust-libp2p/blob/f701b24ec0f99be49444a6e7de950c66b01b2f3f/misc/multistream-select/src/negotiated.rs#L117-L127

For context, this object is a stream onto which a protocol has been negotiated. Because the negotiation is reported in the API has having succeeded before the underlying stream has been flushed, reading on the stream also has the side effect of flushing the stream.

However, if an error happens when flushing, we don't keep track of it, meaning that if the API user then calls `poll_flush` on the `Negotiated`, it will effectively call `pull_flush` a second time on the underlying stream after the first time has errored.

I don't know if this is the cause of _this_ bug, but it is certainly a bug.

**Comment by tomaka** [comment] 2022-06-13 08:31
Actual, what happens, I think is:

The yamux muxer reads from the connection, which calls `Negotiated::poll_read`. `Negotiated::poll_read` calls `QuickSink::poll_flush`, which returns an error, and the error is returned from `poll_read`.

Yamux detects the errors, and when yamux detects an error when reading, [it switches to "shutdown mode"](https://github.com/libp2p/rust-yamux/blob/058010157e5c58976ce0fe78a84bf88ec9dd8656/src/connection.rs#L333-L338) and tries to close the connection in a clean way. This closing calls `Negotiated::poll_close`, which calls `QuickSink::poll_flush` again, which panics.

**Comment by NZT48** [comment] 2022-07-24 21:36
I updated my parachain to Polkadot 0.9.26 dependencies and this issue is breaking node after around 100 blocks.

**Comment by mxinden** [comment] 2022-07-27 05:38
> The yamux muxer reads from the connection, which calls `Negotiated::poll_read`. `Negotiated::poll_read` calls `QuickSink::poll_flush`, which returns an error, and the error is returned from `poll_read`.
> 
> Yamux detects the errors, and when yamux detects an error when reading, [it switches to "shutdown mode"](https://github.com/libp2p/rust-yamux/blob/058010157e5c58976ce0fe78a84bf88ec9dd8656/src/connection.rs#L333-L338) and tries to close the connection in a clean way. This closing calls `Negotiated::poll_close`, which calls `QuickSink::poll_flush` again, which panics.

In such case `libp2p-core` would never call `close` on the `StreamMuxer`, though the line below from the panic above indicates that:

```
Mar 24 02:52:40 ip-172-31-13-88 nimiq-client[36147]:   16: <libp2p_yamux::Yamux<S> as libp2p_core::muxing::StreamMuxer>::close
Mar 24 02:52:40 ip-172-31-13-88 nimiq-client[36147]:   17: <libp2p_core::muxing::Wrap<T> as libp2p_core::muxing::StreamMuxer>::close
```

@tomaka am I missing something?

**Comment by mxinden** [comment] 2022-07-27 05:42
@NZT48 @hrxi @jasl @doutv

It would be very helpful to get more logs right before (~10 seconds) a crash like the one above. Any chance one of you can provide a log output on debug level `RUST_LOG=debug` with the logs 10 seconds before up until the crash?

**Comment by NZT48** [comment] 2022-07-27 15:46
@mxinden Thanks for helping, here are the logs with 10 seconds before: https://we.tl/t-6TuATzVqV4

**Comment by mxinden** [comment] 2022-08-01 06:01
A suspicion I have:

When closing the `Yamux` muxer, we call `inner.control.poll_close` and `inner.incoming.poll_next_unpin` concurrently.

https://github.com/libp2p/rust-libp2p/blob/master/muxers/yamux/src/lib.rs#L132-L150

This could result in both the `control_command` and the `frame` `Future` to be ready at the same time.

https://github.com/libp2p/rust-yamux/blob/master/src/connection.rs#L492-L504

The `frame` future might be _ready_ with an `Error` from the underlying socket (i.e. here `libp2p-websocket`). Though given that the result of the `control_command` `Future` is handled first, `on_control_command` is called despite `frame` having returned an `Error`. `on_control_command` itself may try to write to the underlying socket, which will panic given that the socket returned an error earlier via the `frame` `Future`.

I suggest I prepare a patch for [rust-yamux](https://github.com/libp2p/rust-yamux). To validate the above assumption, could one of you (e.g. @NZT48 @hrxi @jasl @doutv) then run a version of Polkadot with that patch? You would simply need to build Polkadot with a [dependency override](https://doc.rust-lang.org/cargo/reference/overriding-dependencies.html).

**Comment by mxinden** [comment] 2022-08-01 06:50
@NZT48 @hrxi @jasl @doutv @kpp

Would very much appreciate help testing https://github.com/libp2p/rust-yamux/pull/137. Instructions are in the pull request description.

**Comment by NZT48** [comment] 2022-08-02 07:02
@mxinden It works on my side also :)

**Comment by jasl** [comment] 2022-08-02 07:05
Running nearly a day with patched binaries, haven't crash yet

**Comment by mxinden** [comment] 2022-08-02 07:15
@NZT48 @jasl those are wonderful news. Would you mind keeping those deployments running for a bit longer, just to make sure?

**Comment by jasl** [comment] 2022-08-02 08:42
> @NZT48 @jasl those are wonderful news. Would you mind keeping those deployments running for a bit longer, just to make sure?

that's no problem, I patched our testnet so it will keep running

**Comment by mxinden** [comment] 2022-08-03 12:56
Will try to prepare a proper patch for `yamux` tomorrow. This can be released as patch release, i.e. `yamux` `v0.10.2` and thus only needs an update in the Polkadot `Cargo.lock`.

**Comment by mxinden** [comment] 2022-08-04 03:25
I prepared https://github.com/libp2p/rust-yamux/pull/138, which in my eyes represents a valid bug fix, replacing https://github.com/libp2p/rust-yamux/pull/137. https://github.com/libp2p/rust-yamux/pull/138 still needs to pass review.

Given that this is a very subtle issue, and given that https://github.com/libp2p/rust-yamux/pull/138 differs from https://github.com/libp2p/rust-yamux/pull/137, I would appreciate help testing https://github.com/libp2p/rust-yamux/pull/138 as well. 

@NZT48 @hrxi @jasl @doutv @kpp in case one of you has more capacity to run tests, would you mind deploying https://github.com/libp2p/rust-yamux/pull/138 on one of your test instances?

**Comment by jasl** [comment] 2022-08-04 12:02
> I prepared [libp2p/rust-yamux#138](https://github.com/libp2p/rust-yamux/pull/138), which in my eyes represents a valid bug fix, replacing [libp2p/rust-yamux#137](https://github.com/libp2p/rust-yamux/pull/137). [libp2p/rust-yamux#138](https://github.com/libp2p/rust-yamux/pull/138) still needs to pass review.
> 
> Given that this is a very subtle issue, and given that [libp2p/rust-yamux#138](https://github.com/libp2p/rust-yamux/pull/138) differs from [libp2p/rust-yamux#137](https://github.com/libp2p/rust-yamux/pull/137), I would appreciate help testing [libp2p/rust-yamux#138](https://github.com/libp2p/rust-yamux/pull/138) as well.
> 
> @NZT48 @hrxi @jasl @doutv @kpp in case one of you has more capacity to run tests, would you mind deploying [libp2p/rust-yamux#138](https://github.com/libp2p/rust-yamux/pull/138) on one of your test instances?

no problem

**Comment by mxinden** [comment] 2022-08-05 02:00
https://github.com/libp2p/rust-yamux/pull/138 is reviewed and approved thanks to @elenaf9 and @thomaseizinger.

@jasl once I get the green light from you, I will cut a release.

**Comment by jasl** [comment] 2022-08-05 06:19
> [libp2p/rust-yamux#138](https://github.com/libp2p/rust-yamux/pull/138) is reviewed and approved thanks to @elenaf9 and @thomaseizinger.
> 
> @jasl once I get the green light from you, I will cut a release.

Great! I can't wait

BTW, could you help to backport the upgrade to polkadot-v0.9.27 ?

**Comment by mxinden** [comment] 2022-08-05 06:29
> > [libp2p/rust-yamux#138](https://github.com/libp2p/rust-yamux/pull/138) is reviewed and approved thanks to @elenaf9 and @thomaseizinger.
> > @jasl once I get the green light from you, I will cut a release.
> 
> Great! I can't wait

Just to make sure, do I understand correctly that you ran https://github.com/libp2p/rust-yamux/pull/138 and that you are not seeing any panics @jasl?

> BTW, could you help to backport the upgrade to polkadot-v0.9.27 ?

I can not, as I am no longer directly involved in the project. Maybe @kpp or @bkchr can help with the backport.

**Comment by jasl** [comment] 2022-08-05 06:31
> > > [libp2p/rust-yamux#138](https://github.com/libp2p/rust-yamux/pull/138) is reviewed and approved thanks to @elenaf9 and @thomaseizinger.
> > > @jasl once I get the green light from you, I will cut a release.
> > 
> > 
> > Great! I can't wait
> 
> Just to make sure, do I understand correctly that you ran [libp2p/rust-yamux#138](https://github.com/libp2p/rust-yamux/pull/138) and that you are not seeing any panics @jasl?
> 
> > BTW, could you help to backport the upgrade to polkadot-v0.9.27 ?
> 
> I can not, as I am no longer directly involved in the project. Maybe @kpp or @bkchr can help with the backport.

For a night I don't see panic

**Comment by mxinden** [comment] 2022-08-05 06:48
`v0.10.2` of the `yamux` crate is now released.

https://github.com/libp2p/rust-yamux/pull/138#issuecomment-1206103021

Thanks everyone for the help!

I am closing here. Since this is a patch release, there is no need to update `libp2p`, but instead an upgrade to `v0.10.2` at the binary level suffices.

**Closed as completed by mxinden** 2022-08-05 06:48 UTC

**Comment by bkchr** [comment] 2022-08-05 07:51
> > > [libp2p/rust-yamux#138](https://github.com/libp2p/rust-yamux/pull/138) is reviewed and approved thanks to @elenaf9 and @thomaseizinger.
> > > @jasl once I get the green light from you, I will cut a release.
> > 
> > Great! I can't wait
> 
> Just to make sure, do I understand correctly that you ran https://github.com/libp2p/rust-yamux/pull/138 and that you are not seeing any panics @jasl?
> 
> > BTW, could you help to backport the upgrade to polkadot-v0.9.27 ?
> 
> I can not, as I am no longer directly involved in the project. Maybe @kpp or @bkchr can help with the backport.

No need to backport this. Parachains can just run cargo update -p yamux to get the latest version of the crate. As this is nothing critical and doesn't happen that often there is no need for a full polkadot release. It can wait and go into the next polkadot release.

**Comment by kpp** [comment] 2022-08-05 11:17
> there is no need to update libp2p

Still the yamux dep in libp2p needs to be increased in order to force people to download the new version upon upgrade.

**Comment by mxinden** [comment] 2022-08-08 06:24
> > there is no need to update libp2p
> 
> Still the yamux dep in libp2p needs to be increased in order to force people to download the new version upon upgrade.

I would expect downstream users to use tools like @dependabot and thus keeping their dependencies up to date. That said, I am happy to merge a pull request updating the `yamux` version in the `libp2p-yamux` crate.

**Comment by tomaka** [comment] 2022-08-08 09:49
> Still the yamux dep in libp2p needs to be increased in order to force people to download the new version upon upgrade.

There's no need to force people. People are expected to understand that they need to run `cargo update` to make bugs go away.
Increasing the version on the other hand prevents people from downgrading to a previous version if they need to.
