### ISSUE TITLE
Close requirements are too strict

### ISSUE THREAD

**Issue by Demi-Marie** [libp2p/rust-libp2p#1380] opened 2020-01-08 19:53 UTC
For UDP-based transports, there is no way to ensure that outstanding data is delivered in the event a transport is dropped.

**Comment by tomaka** [comment] 2020-01-09 13:06
I don't know where that is from, but the phrasing is probably incorrect and should be "ensure that all buffered data is sent out".

**Comment by DemiMarie-parity** [comment] 2020-01-09 20:50
The problem is that sending out buffered data is a blocking operation.  We could do it in `Drop`, but I don't know if it would be wise.

**Comment by tomaka** [comment] 2020-01-10 08:17
Where is that from, so that I can get a precise opinion about it?

**Comment by romanb** [comment] 2020-10-08 12:54
I'm not sure either what requirements are being discussed here. If this is about `poll_close` / `poll_shutdown`, these are simply supposed to flush buffered data. If a transport is just dropped without a proper close, there is no requirement to flush buffered data, as far as I'm aware.

**Comment by tomaka** [comment] 2020-10-08 14:09
I suppose that the context of this question was the QUIC transport. As far as I know its API wouldn't need to be different than the TCP one for instance.
I suggest to close this.

**Closed by tomaka** 2020-10-08 14:09 UTC
Labels: discussion
