### ISSUE TITLE
Second node not building. Error: InvalidMultiaddr

### ISSUE THREAD

**Issue by varun-doshi** [libp2p/rust-libp2p#5155] opened 2024-02-08 19:07 UTC
### Summary

Trying out the default Ping example using Libp2p rust.
Rust version: 1.70.0

I run the first peer using cargo run and get output in terminal:
`Listening on "/ip4/127.0.0.1/tcp/65332"`

But on the running the other peer in another terminal using the command:
`cargo run /ip4/127.0.0.1/tcp/65332`

it doesn't run and provides the following output:
` Running target\debug\p2pRecipe.exe C:/Program Files/Git/ip4/127.0.0.1/tcp/65332 
 Error: InvalidMultiaddr
error: process didn't exit successfully: target\debug\p2pRecipe.exe C:/Program Files/Git/ip4/127.0.0.1/tcp/65332' (exit code: 1)`

### Expected behavior

I'm expecting the second peer to run and ping pong to take place between the two nodes

### Actual behavior

Only the first peer runs and keeps waiting for any event

### Relevant log output

```shell
Finished dev [unoptimized + debuginfo] target(s) in 0.43s
     Running `target\debug\p2pRecipe.exe 'C:/Program Files/Git/ip4/127.0.0.1/tcp/65332'`Error: InvalidMultiaddr
error: process didn't exit successfully: `target\debug\p2pRecipe.exe 'C:/Program Files/Git/ip4/127.0.0.1/tcp/65332'` (exit code: 1)
```

### Version

futures = "0.3.30"
libp2p = { version="0.52.4", features = ["noise", "ping", "tcp", "tokio", "yamux"] }
tokio = { version = "1.35.1", features = ["full"] }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

### Would you like to work on fixing this bug ?

Yes

**Comment by aditya172926** [comment] 2024-02-11 16:01
I am not able to reproduce the error. The ping example works fine for me.
Doesn't look like a crate bug.

My system config:
rust version:  1.74.1
libp2p: 0.52

**Comment by dariusc93** [comment] 2024-02-12 01:09
Could you provide any code? The ping example works fine, but it looks like you may have altered the code. Also, if you are running the code twice on the same machine, make sure the port number is different for each since it would have already been assigned to one address (in this case "65332" is assigned on one node, so it cannot be used on the second node).

**Comment by thomaseizinger** [comment] 2024-02-12 01:25
> Running `target\debug\p2pRecipe.exe 'C:/Program Files/Git/ip4/127.0.0.1/tcp/65332'`Error: InvalidMultiaddr

This log suggests that the path to the program is also passed as an argument which obviously cannot be parsed as a multiaddress.

**Closed as not planned by thomaseizinger** 2024-02-12 01:25 UTC

**Comment by varun-doshi** [comment] 2024-02-12 04:51
Here is the code:


`
use futures::prelude::*;
use libp2p::{noise, ping, swarm::SwarmEvent, tcp, yamux, Multiaddr};
use std::{error::Error, time::Duration};
use tracing_subscriber::EnvFilter;

#[tokio::main]
async fn main() -> Result<(), Box<dyn Error>> {
    let _ = tracing_subscriber::fmt()
        .with_env_filter(EnvFilter::from_default_env())
        .try_init();

    let mut swarm = libp2p::SwarmBuilder::with_new_identity()
        .with_tokio()
        .with_tcp(
            tcp::Config::default(),
            noise::Config::new,
            yamux::Config::default,
        )?
        .with_behaviour(|_| ping::Behaviour::default())?
        .with_swarm_config(|cfg| cfg.with_idle_connection_timeout(Duration::from_secs(u64::MAX)))
        .build();

    swarm.listen_on("/ip4/0.0.0.0/tcp/0".parse()?)?;

    // Dial the peer identified by the multi-address given as the second
    // command-line argument, if any.
    if let Some(addr) = std::env::args().nth(1) {
        let remote: Multiaddr = addr.parse()?;
        println!("The input:{:?}", std::env::args().nth(1));
        swarm.dial(remote)?;
        println!("Dialed {addr}")
    }

    loop {
        match swarm.select_next_some().await {
            SwarmEvent::NewListenAddr { address, .. } => println!("Listening on {address:?}"),
            SwarmEvent::Behaviour(event) => println!("{event:?}"),
            _ => {}
        }
    }
}
`


On further trying to debug, I got this error:

I was trying the debug(just added a few println statements) and now on running the second peer this is what pops up

`error: linking with link.exe failed: exit code: 1104`

`note: LINK : fatal error LNK1104: cannot open file 'D:\VSCode Rust\p2pRecipe\target\debug\deps\p2pRecipe.exe'`

**Comment by thomaseizinger** [comment] 2024-02-13 09:22
I don't have a windows machine so I can't reproduce this. Can you use WSL instead?

**Comment by aditya172926** [comment] 2024-02-13 10:56
> Here is the code:
> 
> ` use futures::prelude::*; use libp2p::{noise, ping, swarm::SwarmEvent, tcp, yamux, Multiaddr}; use std::{error::Error, time::Duration}; use tracing_subscriber::EnvFilter;
> 
> #[tokio::main] async fn main() -> Result<(), Box> { let _ = tracing_subscriber::fmt() .with_env_filter(EnvFilter::from_default_env()) .try_init();
> 
> ```
> let mut swarm = libp2p::SwarmBuilder::with_new_identity()
>     .with_tokio()
>     .with_tcp(
>         tcp::Config::default(),
>         noise::Config::new,
>         yamux::Config::default,
>     )?
>     .with_behaviour(|_| ping::Behaviour::default())?
>     .with_swarm_config(|cfg| cfg.with_idle_connection_timeout(Duration::from_secs(u64::MAX)))
>     .build();
> 
> swarm.listen_on("/ip4/0.0.0.0/tcp/0".parse()?)?;
> 
> // Dial the peer identified by the multi-address given as the second
> // command-line argument, if any.
> if let Some(addr) = std::env::args().nth(1) {
>     let remote: Multiaddr = addr.parse()?;
>     println!("The input:{:?}", std::env::args().nth(1));
>     swarm.dial(remote)?;
>     println!("Dialed {addr}")
> }
> 
> loop {
>     match swarm.select_next_some().await {
>         SwarmEvent::NewListenAddr { address, .. } => println!("Listening on {address:?}"),
>         SwarmEvent::Behaviour(event) => println!("{event:?}"),
>         _ => {}
>     }
> }
> ```
> 
> } `
> 
> On further trying to debug, I got this error:
> 
> I was trying the debug(just added a few println statements) and now on running the second peer this is what pops up
> 
> `error: linking with link.exe failed: exit code: 1104`
> 
> `note: LINK : fatal error LNK1104: cannot open file 'D:\VSCode Rust\p2pRecipe\target\debug\deps\p2pRecipe.exe'`

Tried this on a Windows OS setup.
Still not able to reproduce the error. The code works fine, just correcting the return type of the main function 
`async fn main() -> Result<(), Box<dyn Error>> {...}` like it is in the example.

**Comment by aditya172926** [comment] 2024-02-13 11:07
Link error looks like a microsoft linker is failing to open the .exe file.
This points to the improper, outdated or no installation of Microsoft Windows SDK.

Try upgrading your downloads from MS Visual studio. @varun-doshi
